In [10]:
import numpy as np
import pandas as pd

In [20]:
df=pd.read_csv("/content/Churn_Modelling - Churn_Modelling.csv")
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [13]:
#Find the total number of customers in each country.

a = df.groupby("Geography")["CustomerId"].count().reset_index()
a

  Geography  CustomerId
0    France        5014
1   Germany        2509
2     Spain        2477

In [14]:
# Find the average credit score of customers based on gender.

d = df.groupby("Gender")["CreditScore"].mean().reset_index()
d

   Gender  CreditScore
0  Female   650.831389
1    Male   650.276892

In [15]:
d = df["Exited"].value_counts().reset_index()
d

   Exited  count
0       0   7963
1       1   2037

In [16]:
q4=df.groupby('Geography')['Balance'].mean().reset_index(name='Avg_balance')
q4

  Geography    Avg_balance
0    France   62092.636516
1   Germany  119730.116134
2     Spain   61818.147763

In [17]:
q5 = df[df["Exited"] == 1].groupby("Age")["CustomerId"].count().reset_index()
q5

    Age  CustomerId
0    18           2
1    19           1
2    20           2
3    21           3
4    22          12
5    23           6
6    24          14
7    25           6
8    26          14
9    27          13
10   28          23
11   29          28
12   30          24
13   31          33
14   32          32
15   33          44
16   34          33
17   35          57
18   36          53
19   37          62
20   38          63
21   39          72
22   40          89
23   41          69
24   42          77
25   43          88
26   44          73
27   45          87
28   46          91
29   47          77
30   48          80
31   49          75
32   50          71
33   51          66
34   52          64
35   53          40
36   54          51
37   55          48
38   56          50
39   57          38
40   58          29
41   59          30
42   60          32
43   61          21
44   62          21
45   63          18
46   64          12
47   65           8
48   66           7
49   67           5
50   68           6
51   69           2
52   70           4
53   71           7
54   72           1
55   73           1
56   74           1
57   84           1

In [18]:
df= df.groupby("IsActiveMember")["EstimatedSalary"].mean().reset_index(name="Avg_EstimatedSalary")
df

   IsActiveMember  Avg_EstimatedSalary
0               0        100767.203854
1               1         99452.965894

In [21]:
 df[df["Exited"] == 1].groupby("NumOfProducts").size().reset_index()

   NumOfProducts     0
0              1  1409
1              2   348
2              3   220
3              4    60

In [22]:
# 8. Create a separate DataFrame containing country and region information, merge it with the
# main dataset using pd.merge(), and then find the average balance and average estimated
# salary by region.

In [23]:
region_df = pd.DataFrame({
    'Geography': ['France', 'Germany', 'Spain'],
    'Region': ['Western Europe', 'Central Europe', 'Southern Europe']
})
region_df

  Geography           Region
0    France   Western Europe
1   Germany   Central Europe
2     Spain  Southern Europe

In [24]:
df_merge = pd.merge(region_df, df, on='Geography')

In [25]:
df_merge.groupby('Region')['Balance'].mean('Balance').reset_index(name='Avg_balance')

            Region    Avg_balance
0   Central Europe  119730.116134
1  Southern Europe   61818.147763
2   Western Europe   62092.636516

In [26]:
df_merge.groupby('Region')['EstimatedSalary'].mean('EstimatedSalary').reset_index(name='Avg_EstimatedSalary')

            Region  Avg_EstimatedSalary
0   Central Europe        101113.435102
1  Southern Europe         99440.572281
2   Western Europe         99899.180814