In [ ]:
#Pandas--> pandas is open source library which is used for handle data manipulations

In [1]:
import pandas as pd

In [ ]:
# data structure of pandas::
#1 Series ---> It stores only values not column and it is one-dimensional
#2 Dataframe___ it store values with column name and it is multi-dimensional

In [6]:
df=pd.Series([1,45,78,90])
df

0     1
1    45
2    78
3    90
dtype: int64

In [ ]:
# data frame

In [ ]:
a={
    "Emp_ID" : [1,2,3,4,5],
    "Name"  :['sam','mohit','raj','Rahul','Aniket'],
    "Department": ['IT','Sales','IT','IT','Sales'],
    "Salary" :[20000,25000,30000,31000,26000]

}

In [ ]:
type(a)

dict

In [ ]:
df=pd.DataFrame(a)
df

   Emp_ID    Name Department  Salary
0       1     sam         IT   20000
1       2   mohit      Sales   25000
2       3     raj         IT   30000
3       4   Rahul         IT   31000
4       5  Aniket      Sales   26000

In [ ]:
# Export this data into csv

In [ ]:
df.to_csv("Emp_data.csv")

In [ ]:
# Export this data into Excel

In [ ]:
df.to_excel("New_emp_data.xlsx")

In [ ]:
# inport the data

In [ ]:
a=pd.read_csv("/content/Emp_data.csv")
a

   Unnamed: 0  Emp_ID    Name Department  Salary
0           0       1     sam         IT   20000
1           1       2   mohit      Sales   25000
2           2       3     raj         IT   30000
3           3       4   Rahul         IT   31000
4           4       5  Aniket      Sales   26000

In [ ]:
b=pd.read_csv("/content/Phonedata.csv")

b.head(5)

,Phone Name,Rating,Storage,Display,DTBslk 3,Battery,Guarnty,off_price,Actual price,OFF
0,"OnePlus 13s 5G (Black Velvet, 256 GB)",4.6,12 GB RAM | 256 GB ROM,16.05 cm (6.32 inch) Display,50MP Rear Camera,5850 mAh Battery,1 Year Warranty,"₹49,405","₹57,999",14% off
1,"OnePlus 9 5G (Astral Black, 128 GB)",3.8,8 GB RAM | 128 GB ROM,16.64 cm (6.55 inch) Display,48MP Rear Camera,4500 mAh Battery,12 months,"₹49,999",NaN,NaN
2,"OnePlus 13s 5G (Green Silk, 256 GB)",4.6,12 GB RAM | 256 GB ROM,16.05 cm (6.32 inch) Display,50MP Rear Camera,5850 mAh Battery,1 Year Warranty,"₹49,857","₹57,999",14% off
3,"OnePlus 15R 5G (Charcoal Black, 256 GB)",4.6,12 GB RAM | 256 GB ROM,17.35 cm (6.83 inch) Display,50MP Rear Camera,7400 mAh Battery,1 year manufacturer warranty for device and 6 ...,"₹48,490","₹54,999",11% off
4,"OnePlus 13s 5G (Pink Satin, 256 GB)",4.6,12 GB RAM | 256 GB ROM,16.05 cm (6.32 inch) Display,50MP Rear Camera,5850 mAh Battery,1 Year Warranty,"₹49,905","₹57,999",13% off