In [8]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv("/content/supply_chain - supply_chain.csv")
df.head(5)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [10]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [11]:
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.deafults="plotly white"

In [12]:
avg_lead_time=df.groupby('Product type')['Lead time'].mean().reset_index()
avg_lead_time

  Product type  Lead time
0    cosmetics  13.538462
1     haircare  18.705882
2     skincare  18.000000

In [13]:
avg_manufacturing_costs=df.groupby('Product type')['Manufacturing costs'].mean().reset_index()
avg_manufacturing_costs

  Product type  Manufacturing costs
0    cosmetics            43.052740
1     haircare            48.457993
2     skincare            48.993157

In [14]:
result=pd.merge(avg_lead_time,avg_manufacturing_costs,on='Product type')
result.rename(columns={'Lead time' : 'Average Lead Time',
                       'Manufacturing costs': 'Average Manufacturing Costs'},
              inplace=True)

print(result)

  Product type  Average Lead Time  Average Manufacturing Costs
0    cosmetics          13.538462                    43.052740
1     haircare          18.705882                    48.457993
2     skincare          18.000000                    48.993157

In [15]:
# Analysis SKU --

In [16]:
revenue_chart=px.line(df, x='SKU',
                      y='Revenue generated',
                      title='Revenue Generated by SKU')
revenue_chart.show()

In [17]:
stock_chart=px.line(df, x= 'SKU',
                    y='Stock levels',
                    title='Stock Levels by SKU')

stock_chart.show()

In [18]:
order_quantity_chart=px.bar(df, x='SKU',
                            y='Order quantities',
                            title='Order Quantity by SKU')
order_quantity_chart

In [19]:
Shipping_cost_chart=px.bar(df , x='Shipping carriers',
                           y='Shipping costs',
                           title='Shipping costs by carrier')
Shipping_cost_chart

In [20]:
df.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [22]:
Transpormation_chart = df.groupby('Transportation modes')['Shipping costs'].mean().reset_index()


pie_chart = px.pie(Transpormation_chart, values = 'Shipping costs',
                   names = 'Transportation modes',
                   title = 'Shipping costs',
                   hover_data = ['Shipping costs'],
                   hole = 0.5,
                   color_discrete_sequence = px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition = 'inside', textinfo = 'percent+label')
pie_chart.show()