In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/supply_chain - supply_chain.csv")
df.head(5)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [4]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [5]:
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.deafults="plotly white"

In [6]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239830,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976920,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [7]:
#now lets get started with analyzing the supply chain by looking at the relationship between the price of the products and the revenue genrated by them

In [9]:
fig=px.scatter(df , x='Price',
               y='Revenue generated',
               color='Product type',
               hover_data=['Number of products sold'],
               trendline='ols')
fig.show()

In [19]:
sales_data = df.groupby('Product type')['Number of products sold'].sum().reset_index()
# sales_data

pie_chart = px.pie(sales_data, values = 'Number of products sold',
                   names = 'Product type',
                   title = 'Sales by Product Type',
                   hover_data = ['Number of products sold'],
                   hole = 0.5,
                   color_discrete_sequence = px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition = 'inside', textinfo = 'percent+label')
pie_chart.show()

In [23]:
total_revenue=df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig=go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                     y=total_revenue['Revenue generated']))
fig.update_layout(title='Total Revenue by Shipping carrier',
                  xaxis_title='Shipping Carrier',
                  yaxis_title='Revenue Generate')
fig.show()

In [32]:
sales_data = df.groupby('Product type')['Defect rates'].sum().reset_index()

pie_chart = px.pie(
    sales_data,
    values='Defect rates',
    names='Product type',
    title='Defect Rates by Product Type',
    hover_data=['Defect rates'],
    hole=0.5,
    color_discrete_sequence=px.colors.qualitative.Pastel
)

pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()